language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - julia --check-bounds=yes -e 'Pkg.init(); Pkg.add("DSP"); Pkg.clone(pwd()); Pkg.build("LiquidDSP"); Pkg.test("LiquidDSP"; coverage=true)'
after_success:
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("LiquidDSP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi